- name: install httpd
  hosts: test
  become: yes
  vars:
    - a: latest
    - b: absent
    - c: started
    - d: restarted
  tasks:
    - name: install httpd software
      yum:
        name: httpd
        state: "{{a}}"
    - name: removing existing file
      file:
        path: /var/www/html/index.html
        state: "{{b}}"
    - name: creating new file
      file:
        path: /var/www/html/index.html
        state: "{{b}}"
    - name: creating new file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: adding content in html
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>WELCOME TO HTTPD SERVER</h1>
    - name: start httpd
      service:
        name: httpd
        state: "{{d}}"
